//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelpClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ClassSet
    {
        public int Id { get; set; }
        public string PsnName { get; set; }
        public System.DateTime ClassDate { get; set; }
        public string ClassType { get; set; }
        public string ClassMaster { get; set; }
        public string WorkRoom { get; set; }
    }
}
