//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelpClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HolidayDuty
    {
        public int Id { get; set; }
        public string PsnId { get; set; }
        public string PsnName { get; set; }
        public byte[] Pic { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    }
}
