//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelpClass
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VisitAppEntities : DbContext
    {
        public VisitAppEntities()
            : base("name=VisitAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_PersonBasic> T_PersonBasic { get; set; }
        public virtual DbSet<T_HolidayDuty> T_HolidayDuty { get; set; }
        public virtual DbSet<T_OuterWorkder> T_OuterWorkder { get; set; }
        public virtual DbSet<T_ClassSet> T_ClassSet { get; set; }
        public virtual DbSet<T_DeviceInfo> T_DeviceInfo { get; set; }
    
        public virtual int P_GetKaiGongCount(Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime)
        {
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("startTime", startTime) :
                new ObjectParameter("startTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("endTime", endTime) :
                new ObjectParameter("endTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_GetKaiGongCount", startTimeParameter, endTimeParameter);
        }
    }
}
